### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by urherenow** [Steveice10/ctrcommon#1]
First, it couldn't find 3ds.h. I have devkitarm and ctrulib installed properly. To get past this error, I tried copying the includes from ctrulib over. Now, it goes further (with a bunch of warnings) and errors out with:

x:/devkitPro/devkitARM/projects/ctrcommon-master/source/ctrcommon/app.cpp:265:61
: error: 'NS_RebootToTitle' was not declared in this scope
     Result res = NS_RebootToTitle(app.mediaType, app.titleId);

seems there's something else missing besides simply having devkitarm and typing "make"...

**Comment by Steveice10** [comment]
If it can't find 3ds.h, your environment is likely setup wrong. The other issue is likely because you don't have the latest ctrulib. ctrcommon requires ctrulib to be built from the latest source.

**Comment by urherenow** [comment]
I'll have to check out my environment then. I've compiled other 3ds stuff just today without issue, but I did have to install Visual Studio for some crap not too long ago. I suppose that could have messed things up...

**Comment by urherenow** [comment]
Already tried compiling ctrulib fresh from the git repo. Did make, and make install with no issues on that one. Just double-checked my environment as well. I see nothing wrong...
