### ISSUE TITLE
gputDrawString() crashes for empty strings

### ISSUE THREAD

**Issue by d0k3** [Steveice10/ctrcommon#4]
Graceful failing (ie. just doing nothing) would be expected. See, f.e. C function printf().

**Comment by Steveice10** [comment]
Fixed in https://github.com/Steveice10/ctrcommon/commit/19daff7532fc319d625e616a52eed291d4f8447f?diff=unified

I'm guessing the GPU just doesn't like empty VBOs? I didn't think it would crash as it was, but it shouldn't now.
