### ISSUE TITLE
Error: Unrecognised key: "ExeFs". >_<

### ISSUE THREAD

**Issue by Voxel-Studios** [Steveice10/ctrcommon#7]
Don't know if it's because you updated Makerom, but I've been having trouble compiling both CIAs and CCIs now.

Basically, I keep getting the error stated in the title, and it says it fails to process the RSF file.

therefore, is there anything I need to tweak for building to work?

**Comment by Steveice10** [comment]
Can you try building with the latest commit of ctrcommon?

**Comment by Voxel-Studios** [comment]
I tried to build it just now, but here's the output I keep getting:

> "make" 
make[1]: git: Command not found
make[1]: *** [submodules] Error 127
"make": *** [build] Error 2

> Process Exit Code: 2
> Time Taken: 00:07

**Comment by hartmannaf** [comment]
There are two ways to fix this, install git and add it to your path or to remove the two git Command from the makefile.

**Comment by Voxel-Studios** [comment]
What exactly is git?

**Comment by hartmannaf** [comment]
Its a comand line tool to use git repositories like github. It allows you to clone repositorzs and update them. The used comand updates the libkhax submodule, from an other repository.

**Comment by Voxel-Studios** [comment]
Ah, I see now! I'll install it and see if I can build it again.

**Comment by Voxel-Studios** [comment]
C:\Users\User\Downloads\ctrcommon-master\ctrcommon-master>make
fatal: Not a git repository (or any of the parent directories): .git
make[1]: *** [submodules] Error 128
make: *** [build] Error 2

**Comment by hartmannaf** [comment]
It seams you have downloaded the zip, please
Use "git clone (ctrcommon andress showen on his main page)" to clone it for as an repository.

**Comment by Voxel-Studios** [comment]
okay, so I did that, and I have no idea where the hell it's cloned to. :/

**Comment by hartmannaf** [comment]
The directory you where with your console, simply hold shift while rightklicking in a folder and click open comandline here to open the cmd directly in a specific folder.

**Comment by Voxel-Studios** [comment]
okay, so it's building now, but it's returning "fatal error: 3ds.h: no such file or directory".
Even though I am confident I have set up ctrulib correctly.

**Comment by hartmannaf** [comment]
Have you installed the devkit pro?

**Comment by Voxel-Studios** [comment]
yes. EVRYTHING is set up.

**Comment by Voxel-Studios** [comment]
By that, I meant devkit pro is set up. I haven't actually had any success still.

**Comment by twocows** [comment]
"fatal error: 3ds.h: no such file or directory" That means that the compiler can't find 3ds.h when it's trying to compile the source. It looks like that's pulled in through ctrulib ( https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds.h ), which is required to build this project.

**Comment by Voxel-Studios** [comment]
I know that.

**Comment by hartmannaf** [comment]
Do you habe an environment variable for ctrulib?

**Comment by Voxel-Studios** [comment]
I added both C:\Devkitpro\libctru and C:\Devkitpro\libctru\include. It still didn't work..

**Comment by Voxel-Studios** [comment]
*added them both to PATH. Did I do the right thing?

**Comment by hartmannaf** [comment]
There need to be a ctrulib enviroment variable. Its directly used by make in the makefiles.

**Comment by Voxel-Studios** [comment]
what do I name the new environment variable? just "ctrulib"?

**Comment by Voxel-Studios** [comment]
Okay, so I have built the latest commit, but still no change, I'm afraid. There's definitely something wrong with Makerom. It still tells me that there is an unrecognised key "ExeFs" in the RSF file.

**Comment by hartmannaf** [comment]
maybe you didn't update your ctrcommon path enviroment variable, to point to the new path.
I cloned it directly inside of the devkit folder and build it there. Its easy to keep track of the librarys this way.

**Comment by Voxel-Studios** [comment]
Nah, I'm pretty sure I'm using the makerom from the ctrcommon directory (which was installed to my Devkitpro directory.)

Definitely something to do with the RSF file reading IMO.

**Comment by hartmannaf** [comment]
I will test it tomorow.

**Comment by Voxel-Studios** [comment]
Maybe you could perhaps send me your working build of makerom?

**Comment by Steveice10** [comment]
Are you sure you updated the tools in the ctrcommon directory correctly?

**Comment by hartmannaf** [comment]
I tested the newest version, and its fully working.

You need to put your cloned ctrcommon directory inside the devkitpro folder, that is the folder make its searching in.
If you cloned it elsewhere it will not be found. Or maybe you need to run git pull inside the repository again, to get the latest version of ctrcommon.

**Comment by Voxel-Studios** [comment]
Okay, so I've got the paths and variables fully working now. However, the "Unrecognised key: ExeFs" error is still present, making it impossible to compile my homebrew into a CIA. I think it has something to do with the RSF file.

**Comment by Steveice10** [comment]
Open up your ctrcommon folder, open the tools folder, delete "template_cia.rsf" and "template_3ds.rsf", and see what happens if you try again. I already updated the RSF to one that should work fine, "template.rsf".

**Comment by Voxel-Studios** [comment]
Deleted both rsf files you told me about. Then I used your Template.rsf in my project. Result:

[RSF ERROR] 'EnableCrypt' requires a value.
Error processing RSF file.

**Comment by Steveice10** [comment]
Are you not using make_base...?

**Comment by Voxel-Studios** [comment]
what's that, and where do I put it?

**Comment by Steveice10** [comment]
See https://github.com/Steveice10/FBI/blob/master/Makefile for how it's used in citrus, which is very similar, except with the ctrcommon path.

You can continue to use your own Makefile if you wish, but you'll need to update it to reflect the changes made to makerom parameters and what not.

**Comment by Voxel-Studios** [comment]
So do I need to install citrus now?

**Comment by Steveice10** [comment]
No.

**Comment by Voxel-Studios** [comment]
Okay then, I'll give it a shot.
